name: tests

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        node: ['12']
    name: test and deploy
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: yarn
      - run: yarn test
      - run: yarn build
      - run: |
          npm config set '//registry.npmjs.org/:_authToken' "${NPM_AUTH_TOKEN}"
          npm publish
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
